FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalamos las dependencias necesarias para los nuevos scripts
RUN pip install --no-cache-dir fastmcp uvicorn pandas joblib radon fpdf pypdf python-docx scikit-learn

COPY . .

# Comando por defecto (se sobreescribe en el JSON)
CMD ["python", "main.py"]